[font]
size = 12

[font.bold]
family = "terminessnerdfontmono"
style = "Bold"

[font.bold_italic]
family = "terminessnerdfontmono"
style = "Bold Italic"

[font.italic]
family = "terminessnerdfontmono"
style = "Italic"

[font.normal]
family = "terminessnerdfontmono"
style = "Regular"

# Default colors
[colors.primary]
background = '#000000'
foreground = '#aaaaaa'

# Normal colors
[colors.normal]
black      = '#0c0c0c'
red        = '#c50f1f'
green      = '#13a10e'
yellow     = '#c19c00'
blue       = '#0037da'
magenta    = '#881798'
cyan       = '#3a96dd'
white      = '#cccccc'

# Bright colors
[colors.bright]
black      = '#767676'
red        = '#e74856'
green      = '#16c60c'
yellow     = '#f9f1a5'
blue       = '#3b78ff'
magenta    = '#b4009e'
cyan       = '#61d6d6'
white      = '#f2f2f2'
